MD003:
  style: atx

MD004:
  style: consistent

MD005:
  indent: 2

MD007: 2

MD013:
  code_blocks: false
  line_length: 915
  tables: false

MD029: one

MD033: false

MD034: false

MD035: consistent

MD046: false
